### ISSUE TITLE
Any plan to get this to work with DNN 9.2

### ISSUE THREAD

**Issue by toshno** [ventrian/Property-Agent#14]
When I install an add module to page I get this error: Error: Property Agent is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. at Ventrian.PropertyAgent.PropertyAgentBase.get_IsEditor() at Ventrian.PropertyAgent._Default.ReadQueryString() at Ventrian.PropertyAgent._Default.Page_Initialize(Object sender, EventArgs e) --- End of inner exception stack trace ---

**Comment by nichord** [comment]
I am working on modifying code to get this to work with DNN 9.2, which requires the removal of dependency of SharpZipLib and updating APIs that were removed. I have the code mostly working, for DNN9.2. I needed to modify for my customer to get this working quickly. A bit of a hack job, but maybe one of these guys who know this better can look through my hack and merge it together using my updates and get a better release. See my fork.. nichord/Property-Agent. I know my fork immediately needs a fix for uploading templates to correct directory. The files unzip to /template directory instead of /template/templatename directory. Not sure I will get much time to work on this any time soon...

**Comment by jdaniels517** [comment]
Any updates on this?  I need to put my long time Property Agent customer on my new DNN instance (9.2) and there's just no other decent Real Estate modules out there.  Would really like to be able to use this even if it meant sacrificing some functionality.

**Comment by JoeAucoin** [comment]
I also use this module on a lot of sites . . . .

**Comment by mortezakermani** [comment]
Hi,
Benvis just published a patch for this module that makes ventrian property agent compatible with dnn 9.2 and later at dnn store:

https://store.dnnsoftware.com/home/product-details/ventrian-property-agent-patch

@JoeAucoin 
@jdaniels517

**Comment by toshno** [comment]
$75 for just patch, it should have improvements too for that price and support period. 9.3 is almost near release
